### ISSUE TITLE
In Admin "vs" User Seminar view, list Users Profile data (like phone number, homepage, address)

### ISSUE THREAD

**Issue by fwolfst** [ecovillage/neseri#13]
In the view where an admin sees the admin- and the user copy of a seminar side-by-side, the admin probably wants to contact all referees ("instructors") of the given Seminar.

In the table at the very bottom of that page the contact data from the users profile should appear.

Work can happen in the master-branch which is probably somewhat dirty - I will try to clean the state up next week.

**Comment by TheRealSyler** [comment]
this (https://github.com/TheRealSyler/neseri/commit/5c743a0c52a6118b4b6a1b4be0a3fb17b386d034) commit kind of solves this issue, the only problem is it looks ugly, if i add a column for each the address, homepage etc. it gets cluttered vertically and if i leave it as is there is a lot of space because the other fields in the row require a lot less space, what do you think is better(less ugly)?

**Comment by fwolfst** [comment]
I find it quite okay, actually. Just the table header needs a `colspan=7`. Sure, it will not win a beaty contest, but imho this fixes the issue. Can you add the colspan and fire a PR?

**Comment by fwolfst** [comment]
cherry-picked. thanks.
